"""``bench ci`` — generate / validate a GitHub Actions regression workflow.

Two subcommands:

* ``bench ci init`` — write a stock workflow file that runs a known baseline
  benchmark on a self-hosted GPU runner and fails the build via
  ``bench diff --strict`` if the new envelope regresses the metric envelope
  versus a checked-in baseline at ``.bench/baseline.json``.
* ``bench ci validate`` — parse an existing workflow and verify it has the
  required shape (right triggers, runs ``bench run`` + ``bench diff``, diff
  uses ``--strict`` so regressions actually fail the build).

The workflow body is rendered from a Python ``str`` template (NOT Jinja) so
this module has no extra runtime deps beyond ``pyyaml``, which the CLI
already depends on.
"""

from __future__ import annotations

from pathlib import Path
from typing import Annotated, Any

import typer
import yaml
from rich.console import Console
from rich.table import Table

app = typer.Typer(no_args_is_help=True)
console = Console()
err_console = Console(stderr=True)


# --------------------------------------------------------------------------- #
# Workflow template                                                           #
# --------------------------------------------------------------------------- #
# Single-braced ``{placeholders}`` get filled by ``str.format``. There are no
# literal curly braces in this YAML body, so we don't need to escape any.
# ruff: noqa: E501 — the workflow body must preserve literal line shape; the
# `python -c "..."` step needs to stay on one line so the YAML run-block runs
# it as a single shell command on the runner.
_WORKFLOW_TEMPLATE = """\
# Auto-generated by `bench ci init`. Edit freely — see https://yobitelcomm.github.io/bench/recipes/regression-check
name: bench-regression
on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  bench:
    name: regression
    runs-on: [{runner_labels}]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install bench
        run: |
          export PATH="$HOME/.local/bin:$PATH"
          uv pip install --system inferencebench inferencebench-llm
      - name: Set up dev signing key
        run: |
          mkdir -p .bench
          if [ ! -f .bench/cosign.key ]; then
            python -c "from inferencebench.envelope import generate_dev_keypair; generate_dev_keypair('.bench/cosign.key')"
          fi
      - name: Run benchmark
        env:
          OPENAI_API_KEY: EMPTY
        run: |
          bench run {suite} \\
            --model {model} \\
            --engine {engine} \\
            --base-url http://localhost:8000/v1 \\
            --duration 60 \\
            --signing-mode dev \\
            --dev-key .bench/cosign.key \\
            --output .bench/results
      - name: Diff against baseline
        run: |
          NEW=$(ls -t .bench/results/*.json | head -1)
          if [ -f {baseline} ]; then
            bench diff {baseline} "$NEW" --strict --tolerance {tolerance}
          else
            echo "::warning::No baseline at {baseline} — promoting current run."
            cp "$NEW" {baseline}
          fi
      - name: Upload envelope
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: bench-envelope
          path: .bench/results/
"""


def _format_runner_labels(runner: str) -> str:
    """Turn ``"self-hosted,gpu"`` into ``"self-hosted, gpu"`` for YAML inline-list.

    The generated workflow uses ``runs-on: [<labels>]`` flow-style; we render
    the labels comma-separated with a space, which is the canonical way GH
    Actions docs show multi-label flow-list runners.
    """
    parts = [p.strip() for p in runner.split(",") if p.strip()]
    if not parts:
        msg = "runner must contain at least one label"
        raise typer.BadParameter(msg)
    return ", ".join(parts)


def _render_workflow(
    *,
    suite: str,
    model: str,
    engine: str,
    baseline: str,
    runner: str,
    tolerance: float,
) -> str:
    """Render the workflow YAML body from the template."""
    return _WORKFLOW_TEMPLATE.format(
        runner_labels=_format_runner_labels(runner),
        suite=suite,
        model=model,
        engine=engine,
        baseline=baseline,
        tolerance=tolerance,
    )


@app.command("init")
def ci_init(
    out: Annotated[
        Path,
        typer.Option(
            "--out",
            help="Destination workflow file.",
        ),
    ] = Path(".github/workflows/bench-regression.yml"),
    suite: Annotated[
        str,
        typer.Option("--suite", help="Benchmark suite id to run in CI."),
    ] = "llm.inference.sharegpt-v3",
    model: Annotated[
        str,
        typer.Option("--model", help="Model id passed to ``bench run --model``."),
    ] = "meta-llama/Llama-3.1-8B-Instruct",
    engine: Annotated[
        str,
        typer.Option("--engine", help="Inference engine kind."),
    ] = "vllm",
    baseline: Annotated[
        str,
        typer.Option("--baseline", help="Path (in-repo) to the baseline envelope JSON."),
    ] = ".bench/baseline.json",
    runner: Annotated[
        str,
        typer.Option(
            "--runner",
            help="Comma-separated `runs-on` labels (e.g. 'self-hosted,gpu').",
        ),
    ] = "self-hosted,gpu",
    tolerance: Annotated[
        float,
        typer.Option(
            "--tolerance",
            help="Regression tolerance forwarded to `bench diff --tolerance`.",
        ),
    ] = 0.05,
    force: Annotated[
        bool,
        typer.Option("--force", help="Overwrite an existing workflow file."),
    ] = False,
) -> None:
    """Write a stock GitHub Actions regression-check workflow.

    Refuses to overwrite an existing file unless ``--force`` is passed.
    """
    if out.exists() and not force:
        err_console.print(
            f"[red]Refusing to overwrite[/red] {out} — re-run with [bold]--force[/bold]."
        )
        raise typer.Exit(code=1)

    body = _render_workflow(
        suite=suite,
        model=model,
        engine=engine,
        baseline=baseline,
        runner=runner,
        tolerance=tolerance,
    )

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(body, encoding="utf-8")

    table = Table(title="bench ci init", show_header=False)
    table.add_column("field", style="cyan")
    table.add_column("value", style="bold")
    table.add_row("workflow", str(out))
    table.add_row("suite", suite)
    table.add_row("model", model)
    table.add_row("engine", engine)
    table.add_row("baseline", baseline)
    table.add_row("runner", runner)
    table.add_row("tolerance", f"{tolerance:g}")
    console.print(table)
    console.print(
        f"[green]Wrote[/green] {out}. "
        "Commit it alongside a baseline envelope at "
        f"[bold]{baseline}[/bold] to start gating PRs on regressions."
    )


# --------------------------------------------------------------------------- #
# validate                                                                    #
# --------------------------------------------------------------------------- #
def _iter_step_runs(workflow: dict[Any, Any]) -> list[str]:
    """Return every ``run:`` string across every step of every job.

    Defensive against unexpected shapes: a malformed workflow just yields the
    runs we can find, and the calling checks fail naturally.
    """
    runs: list[str] = []
    jobs = workflow.get("jobs")
    if not isinstance(jobs, dict):
        return runs
    for job in jobs.values():
        if not isinstance(job, dict):
            continue
        steps = job.get("steps")
        if not isinstance(steps, list):
            continue
        for step in steps:
            if isinstance(step, dict) and isinstance(step.get("run"), str):
                runs.append(step["run"])
    return runs


def _check_triggers(workflow: dict[Any, Any]) -> bool:
    """Top-level ``on`` must include either pull_request or workflow_dispatch.

    PyYAML's ``safe_load`` parses the bare YAML 1.1 key ``on:`` as the Python
    bool ``True`` (cousin of the "Norway problem"). We accept either key.
    """
    on: Any = workflow.get("on") if "on" in workflow else workflow.get(True)
    if isinstance(on, str):
        return on in {"pull_request", "workflow_dispatch"}
    if isinstance(on, list):
        return any(t in {"pull_request", "workflow_dispatch"} for t in on)
    if isinstance(on, dict):
        return "pull_request" in on or "workflow_dispatch" in on
    return False


def _check_has_run_and_diff(runs: list[str]) -> tuple[bool, bool]:
    """Return ``(has_bench_run, has_bench_diff)`` over collected run strings."""
    has_run = any("bench run" in r for r in runs)
    has_diff = any("bench diff" in r for r in runs)
    return has_run, has_diff


def _check_diff_strict(runs: list[str]) -> bool:
    """The step containing ``bench diff`` must also include ``--strict``."""
    diff_runs = [r for r in runs if "bench diff" in r]
    if not diff_runs:
        return False
    return all("--strict" in r for r in diff_runs)


@app.command("validate")
def ci_validate(
    workflow_path: Annotated[
        Path,
        typer.Argument(help="Path to the workflow YAML to validate."),
    ] = Path(".github/workflows/bench-regression.yml"),
) -> None:
    """Validate that a workflow file has the right shape for regression checks.

    Exits 0 on all-pass, 1 if any check fails, 2 if the file can't be parsed
    as YAML.
    """
    if not workflow_path.exists():
        err_console.print(f"[red]Workflow not found:[/red] {workflow_path}")
        raise typer.Exit(code=2)

    try:
        raw = workflow_path.read_text(encoding="utf-8")
        parsed: Any = yaml.safe_load(raw)
    except yaml.YAMLError as exc:
        err_console.print(f"[red]YAML parse error:[/red] {exc}")
        raise typer.Exit(code=2) from exc

    if not isinstance(parsed, dict):
        err_console.print(
            f"[red]Workflow root must be a mapping, got {type(parsed).__name__}.[/red]"
        )
        raise typer.Exit(code=2)

    runs = _iter_step_runs(parsed)
    has_run, has_diff = _check_has_run_and_diff(runs)

    checks: list[tuple[str, bool, str]] = [
        (
            "triggers include pull_request or workflow_dispatch",
            _check_triggers(parsed),
            "Add `pull_request:` or `workflow_dispatch:` under top-level `on:`.",
        ),
        (
            "a step runs `bench run`",
            has_run,
            "Add a step that runs `bench run <suite> --model <id> ...`.",
        ),
        (
            "a step runs `bench diff`",
            has_diff,
            "Add a step that runs `bench diff <baseline> <new> ...`.",
        ),
        (
            "`bench diff` uses `--strict`",
            _check_diff_strict(runs),
            "Add `--strict` to the diff invocation so CI fails on regression.",
        ),
    ]

    table = Table(title=f"bench ci validate — {workflow_path}")
    table.add_column("check", style="cyan")
    table.add_column("status", justify="center")
    table.add_column("fix", style="dim")
    for label, ok, fix in checks:
        status = "[green]PASS[/green]" if ok else "[red]FAIL[/red]"
        table.add_row(label, status, "" if ok else fix)
    console.print(table)

    failures = [label for label, ok, _ in checks if not ok]
    if failures:
        err_console.print(f"[red]{len(failures)} check(s) failed:[/red] " + ", ".join(failures))
        raise typer.Exit(code=1)
    console.print("[green]All checks passed.[/green]")
