"""``bench plugin`` — manage benchmark plugins.

Subcommands: list, init, install, info.
Plugin discovery via Python entry points.
"""

from __future__ import annotations

import re
from importlib import metadata
from pathlib import Path
from typing import Annotated

import typer
from rich.console import Console
from rich.table import Table

app = typer.Typer(no_args_is_help=True)
console = Console()
err_console = Console(stderr=True)

_NAME_RE = re.compile(r"^[a-z][a-z0-9-]*$")


def _discover_plugins() -> list[metadata.EntryPoint]:
    """Return all registered plugin entry points (Phase 1: typically empty)."""
    try:
        return list(metadata.entry_points(group="inferencebench.plugins"))
    except TypeError:
        # Pre-3.10 compat path — shouldn't trigger on 3.12
        return list(metadata.entry_points().get("inferencebench.plugins", []))  # type: ignore[attr-defined]


@app.command("list")
def list_plugins() -> None:
    """List installed plugins."""
    eps = _discover_plugins()
    if not eps:
        console.print("[yellow]No plugins installed.[/yellow]")
        console.print("Install one: [bold]pip install inferencebench-llm[/bold]")
        return

    table = Table(title="Installed plugins")
    table.add_column("Name", style="cyan")
    table.add_column("Module", style="dim")
    table.add_column("Distribution", style="green")
    for ep in eps:
        dist = ep.dist.name if ep.dist else "?"
        table.add_row(ep.name, ep.value, dist)
    console.print(table)


@app.command("init")
def init_plugin(
    name: Annotated[str, typer.Argument(help="New plugin name (e.g. 'voice').")],
    kind: Annotated[str, typer.Option("--kind", help="perf, quality, or both.")] = "both",
    modality: Annotated[str, typer.Option("--modality", help="llm, voice, video, 3d, ...")] = "",
) -> None:
    """Scaffold a new plugin package under ``./plugins/<name>/``.

    Creates a self-contained skeleton: pyproject.toml with a registered
    entry point, src package with a plugin class matching the contract from
    ``inferencebench_llm.plugin``, a passing test, and a README stub.
    """
    if not _NAME_RE.match(name):
        err_console.print(
            f"[red]Invalid plugin name:[/red] {name!r} — must match [a-z][a-z0-9-]* "
            "(lowercase, no underscores)."
        )
        raise typer.Exit(code=1)

    target = Path.cwd() / "plugins" / name
    if target.exists():
        err_console.print(f"[red]Target directory already exists:[/red] {target}")
        raise typer.Exit(code=1)

    pkg_name = name.replace("-", "_")
    class_name = "".join(part.capitalize() for part in name.split("-")) + "Plugin"

    src_pkg_dir = target / "src" / f"inferencebench_{pkg_name}"
    tests_dir = target / "tests"
    src_pkg_dir.mkdir(parents=True)
    tests_dir.mkdir(parents=True)

    (target / "pyproject.toml").write_text(
        _PYPROJECT_TEMPLATE.format(name=name, pkg=pkg_name, cls=class_name),
        encoding="utf-8",
    )
    (target / "README.md").write_text(
        _README_TEMPLATE.format(name=name, modality=modality or "<unspecified>", kind=kind),
        encoding="utf-8",
    )
    (src_pkg_dir / "__init__.py").write_text(
        _INIT_TEMPLATE.format(pkg=pkg_name, cls=class_name),
        encoding="utf-8",
    )
    (src_pkg_dir / "plugin.py").write_text(
        _PLUGIN_TEMPLATE.format(
            name=name, cls=class_name, modality=modality or "<unspecified>", kind=kind
        ),
        encoding="utf-8",
    )
    (tests_dir / "test_plugin.py").write_text(
        _TEST_TEMPLATE.format(pkg=pkg_name, cls=class_name, name=name),
        encoding="utf-8",
    )

    console.print(f"[green]Scaffolded plugin[/green] [bold]{name}[/bold] at {target}")
    console.print("Next steps:")
    console.print(f"  [bold]uv sync --all-packages && uv run pytest plugins/{name}/tests/[/bold]")


# --------------------------------------------------------------------------- #
# Templates                                                                   #
# --------------------------------------------------------------------------- #
_PYPROJECT_TEMPLATE = """\
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "inferencebench-{name}"
version = "0.0.0"
description = "InferenceBench plugin: {name}"
readme = "README.md"
requires-python = ">=3.12"
license = {{ text = "Apache-2.0" }}
dependencies = [
    "inferencebench-envelope",
    "inferencebench-harness",
    "pydantic~=2.9",
]

[project.entry-points."inferencebench.plugins"]
"{name}" = "inferencebench_{pkg}.plugin:{cls}"

[tool.hatch.build.targets.wheel]
packages = ["src/inferencebench_{pkg}"]
"""

_README_TEMPLATE = """\
# inferencebench-{name}

InferenceBench plugin for the `{name}` suite (modality: {modality}, kind: {kind}).
Generated by `bench plugin init`. Implement `list_benchmarks`, `validate`, and
`run` in `src/inferencebench_{name}/plugin.py` to wire your benchmark.
"""

_INIT_TEMPLATE = '''\
"""InferenceBench {pkg} plugin package."""

from inferencebench_{pkg}.plugin import {cls}

__all__ = ["{cls}"]
'''

_PLUGIN_TEMPLATE = '''\
"""{cls} — InferenceBench plugin for the ``{name}`` suite.

Modality: {modality}
Kind:     {kind}

Implements the plugin contract every InferenceBench plugin must satisfy:

- :meth:`list_benchmarks` — what benchmark specs are bundled with this plugin
- :meth:`get_benchmark` — look one up by id
- :meth:`validate` — fast sanity check before run
- :meth:`run` — execute a spec and produce a signed envelope
"""

from __future__ import annotations

from typing import Any


class {cls}:
    """Entry point for the ``{name}`` benchmark suite."""

    suite_id = "{name}"
    version = "0.0.0"
    description = "InferenceBench {name} plugin (modality: {modality}, kind: {kind})."

    def list_benchmarks(self) -> list[Any]:
        """Return the BenchmarkSpec list shipped with this plugin."""
        return []

    def get_benchmark(self, benchmark_id: str) -> Any:
        """Look up a benchmark spec by id."""
        for spec in self.list_benchmarks():
            if getattr(spec, "benchmark_id", None) == benchmark_id:
                return spec
        msg = f"benchmark_id not found: {{benchmark_id}}"
        raise KeyError(msg)

    def validate(self, spec: Any, context: Any) -> list[str]:
        """Return a list of human-readable warnings (empty = OK)."""
        return []

    def run(self, spec: Any, context: Any) -> Any:
        """Execute the benchmark and return a SIGNED envelope."""
        msg = "{cls}.run is not implemented yet — fill in the harness wiring."
        raise NotImplementedError(msg)
'''

_TEST_TEMPLATE = '''\
"""Smoke test for the generated {name} plugin."""

from __future__ import annotations

from inferencebench_{pkg} import {cls}


def test_plugin_suite_id() -> None:
    assert {cls}().suite_id == "{name}"
'''


@app.command("install")
def install_plugin(
    package: Annotated[str, typer.Argument(help="Plugin package name (e.g. inferencebench-llm).")],
) -> None:
    """Install a plugin from PyPI.

    Phase 1 stub — ticket 0028. (User can already do this with pip directly.)
    """
    err_console.print(
        f"[yellow][stub][/yellow] bench plugin install [bold]{package}[/bold] — "
        "not yet implemented in v0.0.0 (ticket 0028). Use [bold]pip install[/bold] instead."
    )


@app.command("info")
def info_plugin(
    name: Annotated[str, typer.Argument(help="Plugin name to introspect.")],
) -> None:
    """Show information about an installed plugin."""
    eps = _discover_plugins()
    matched = [ep for ep in eps if ep.name == name]
    if not matched:
        err_console.print(f"[red]Plugin not found:[/red] {name}")
        err_console.print(f"Installed: {[ep.name for ep in eps] or 'none'}")
        raise typer.Exit(code=1)

    ep = matched[0]
    console.print(f"[bold]{ep.name}[/bold]")
    console.print(f"  module:        {ep.value}")
    if ep.dist:
        console.print(f"  distribution:  {ep.dist.name} {ep.dist.version}")
        meta = ep.dist.metadata
        if meta:
            console.print(f"  summary:       {meta.get('Summary', '<none>')}")
            console.print(f"  homepage:      {meta.get('Home-page', '<none>')}")
